"""Adversarial self-tests for the comptox-mcp Track-B scientific-invariants gate.

The gated released object is the SERVER-AUTHORED ``prioritize_risk_signals``
conclusion (a ``BioactivityExposureRatioRecord`` in spine terms). These tests
prove, through the REAL vendored spine engine (no stubbing of the bridge):

1. PRISTINE — the real producer's emitted response passes the strict emission
   contract AND the spine engine (no blocking code).
2. PER-CODE BITE — each ADVERTISED code (BER_NOT_RISK_OR_REGULATORY,
   BER_UNCERTAINTY_AND_CEILING_REQUIRED) bites on a producer-emittable,
   emission-schema-VALID fault, generated by mutating the REAL producer's authored
   conclusion the way a producer regression would.
3. GUARD REJECTS A FORBIDDEN FIELD — an undeclared field at a strict emission level
   is a SOURCE_CONTRACT_VIOLATION that BLOCKS before any projection (closes the
   dead-arm class).
4. NEGATION SAFETY — an honest "not a regulatory risk determination" disclaimer is
   NOT mistaken for a risk/regulatory authorization.
5. HONEST-DROP — the inconclusive band maps faithfully to a passing comparable
   class (BER_REQUIRES_COMPARABILITY is not falsely RED-ed on a pristine
   inconclusive packet).
6. FAIL-CLOSED — an unrecognized projected schemaId blocks rather than sailing
   through as the engine's silent valid:true no-op.
7. DETERMINISM — the projection is byte-stable.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

import pytest

from epacomp_tox.governance import project_to_spine as projector
from epacomp_tox.governance import source_contract
from epacomp_tox.governance import spine_bridge as bridge
from epacomp_tox.governance.errors import SOURCE_CONTRACT_VIOLATION
from epacomp_tox.resources.prioritization import PrioritizationResource
from tests.interop_test_support import (
    StubBioactivityResource,
    StubChemicalResource,
    StubExposureResource,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
PRISTINE_PATH = (
    REPO_ROOT
    / "tests"
    / "fixtures"
    / "governance"
    / "released"
    / "pristine_prioritize_risk_signals.json"
)


# --------------------------------------------------------------------------- #
# helpers — drive the REAL producer so faults are producer-emittable
# --------------------------------------------------------------------------- #


def _real_response(**overrides) -> dict:
    """Run the REAL PrioritizationResource against the stub data sources and
    return its emitted prioritize_risk_signals response (generatedAt stripped for
    byte-stability — it is optional in the strict contract and the gate never reads
    it)."""
    resource = PrioritizationResource(
        api_key="fake",
        chemical_resource=StubChemicalResource(),
        bioactivity_resource=overrides.get("bioactivity", StubBioactivityResource()),
        exposure_resource=overrides.get("exposure", StubExposureResource()),
    )
    res = resource.execute_tool("prioritize_risk_signals", {"dtxsid": "DTXSID7020182"})
    res.get("provenanceSummary", {}).pop("generatedAt", None)
    return res


def _bridge_codes(packet: dict) -> set[str]:
    """source-contract + project + run the REAL engine; collect blocking codes."""
    cf = source_contract.validate_source_packet(packet, corpus="test")
    if cf is not None:
        return {cf.code}
    codes: set[str] = set()
    for obj in projector.project_packet(packet):
        result = bridge.validate_object(obj)
        codes |= set(result.blocking_codes)
    return codes


@pytest.fixture()
def pristine() -> dict:
    return json.loads(PRISTINE_PATH.read_text(encoding="utf-8"))


# --------------------------------------------------------------------------- #
# 1. PRISTINE
# --------------------------------------------------------------------------- #


def test_pristine_fixture_matches_real_producer(pristine: dict) -> None:
    """The committed pristine corpus IS the real producer's emitted shape."""
    assert pristine == _real_response()


def test_pristine_passes_contract_and_engine(pristine: dict) -> None:
    assert source_contract.validate_source_packet(pristine, corpus="pristine") is None
    assert _bridge_codes(pristine) == set()


# --------------------------------------------------------------------------- #
# 2. PER-CODE BITE — each advertised code, on a producer-emittable Ajv-VALID fault
# --------------------------------------------------------------------------- #


def test_ber_not_risk_or_regulatory_bites_on_authored_basis_leak(
    pristine: dict,
) -> None:
    """A producer regression whose authored `basis` LEAKS a risk/regulatory
    downstream-use authorization -> BER_NOT_RISK_OR_REGULATORY bites. The mutated
    basis is a plain string the real producer's basis slot can carry, so the object
    is emission-schema-VALID (not a contract violation)."""
    fault = copy.deepcopy(pristine)
    fault["prioritization"][
        "basis"
    ] = "Derived an acceptable daily intake and a safe level for regulatory submission."
    assert source_contract.validate_source_packet(fault, corpus="fault") is None
    assert "BER_NOT_RISK_OR_REGULATORY" in _bridge_codes(fault)


def test_ber_not_risk_or_regulatory_bites_on_supporting_signal_leak(
    pristine: dict,
) -> None:
    """The leak can also ride a declared supportingSignals entry."""
    fault = copy.deepcopy(pristine)
    fault["prioritization"]["supportingSignals"] = [
        "This margin establishes the reference dose for risk characterization."
    ]
    assert source_contract.validate_source_packet(fault, corpus="fault") is None
    assert "BER_NOT_RISK_OR_REGULATORY" in _bridge_codes(fault)


def test_ber_uncertainty_and_ceiling_required_bites_when_disclosure_dropped(
    pristine: dict,
) -> None:
    """A producer regression that emits a non-inconclusive band but DROPS its
    uncertainty / screening-ceiling disclosure (empty caveats + no data gaps + no
    limitations) -> BER_UNCERTAINTY_AND_CEILING_REQUIRED bites. caveats has no
    minItems in the strict contract, so the fault is emission-schema-VALID."""
    fault = copy.deepcopy(pristine)
    fault["prioritization"]["caveats"] = []
    fault["knownDataGaps"] = []
    fault["limitations"] = []
    assert source_contract.validate_source_packet(fault, corpus="fault") is None
    assert "BER_UNCERTAINTY_AND_CEILING_REQUIRED" in _bridge_codes(fault)


# --------------------------------------------------------------------------- #
# 3. GUARD REJECTS A FORBIDDEN FIELD (the dead-arm fix)
# --------------------------------------------------------------------------- #


def test_guard_rejects_forbidden_field_on_conclusion_block(pristine: dict) -> None:
    """An undeclared field on the strict `prioritization` conclusion block is a
    SOURCE_CONTRACT_VIOLATION that BLOCKS BEFORE projection."""
    fault = copy.deepcopy(pristine)
    fault["prioritization"]["riskDetermination"] = "high"
    finding = source_contract.validate_source_packet(fault, corpus="fault")
    assert finding is not None
    assert finding.code == SOURCE_CONTRACT_VIOLATION
    assert "riskDetermination" in finding.message


def test_guard_rejects_forbidden_field_at_packet_root(pristine: dict) -> None:
    fault = copy.deepcopy(pristine)
    fault["riskClearance"] = "approved"
    finding = source_contract.validate_source_packet(fault, corpus="fault")
    assert finding is not None
    assert finding.code == SOURCE_CONTRACT_VIOLATION


def test_guard_rejects_forbidden_field_on_evidence_slice(pristine: dict) -> None:
    fault = copy.deepcopy(pristine)
    fault["exposureSignal"]["seem"]["smuggled"] = True
    finding = source_contract.validate_source_packet(fault, corpus="fault")
    assert finding is not None
    assert finding.code == SOURCE_CONTRACT_VIOLATION


def test_guard_rejects_unmapped_priority_band(pristine: dict) -> None:
    """A priorityBand outside the declared enum is a contract violation (the
    projection never sees it)."""
    fault = copy.deepcopy(pristine)
    fault["prioritization"]["priorityBand"] = "catastrophic"
    finding = source_contract.validate_source_packet(fault, corpus="fault")
    assert finding is not None
    assert finding.code == SOURCE_CONTRACT_VIOLATION


# --------------------------------------------------------------------------- #
# 4. NEGATION SAFETY — honest disclaimer is not an authorization
# --------------------------------------------------------------------------- #


def test_honest_screening_disclaimer_does_not_false_bite(pristine: dict) -> None:
    """The producer's standing screening caveat ("...is not a regulatory risk
    determination") must NOT be mistaken for a risk/regulatory authorization."""
    # The pristine fixture already carries exactly this caveat.
    assert any(
        "not a regulatory risk determination" in c.lower()
        for c in pristine["prioritization"]["caveats"]
    )
    assert _bridge_codes(pristine) == set()


# --------------------------------------------------------------------------- #
# 5. HONEST-DROP — inconclusive maps faithfully to a passing comparable class
# --------------------------------------------------------------------------- #


def test_inconclusive_band_passes_comparability(pristine: dict) -> None:
    """A faithful inconclusive packet (the producer emits it when core inputs are
    missing) maps to interpretationClass=requires_review and PASSES — the
    honest-dropped BER_REQUIRES_COMPARABILITY is never falsely RED-ed."""

    class _MissingAed(StubBioactivityResource):
        def get_bioactivity_aed(self, dtxsid: str):
            return []

    inconclusive = _real_response(bioactivity=_MissingAed())
    assert inconclusive["prioritization"]["priorityBand"] == "inconclusive"
    obj = projector.project_packet(inconclusive)[0]
    assert obj["interpretationClass"] == "requires_review"
    assert _bridge_codes(inconclusive) == set()


# --------------------------------------------------------------------------- #
# 6. FAIL-CLOSED — unrecognized projected schemaId blocks
# --------------------------------------------------------------------------- #


def test_unrecognized_schema_id_fails_closed() -> None:
    """An object whose schemaId the engine does not recognize must BLOCK, not sail
    through as the engine's silent valid:true no-op."""
    result = bridge.validate_object(
        {"schemaId": "https://schemas.ngra.ai/toxmcp/NotARealObject.v1.schema.json"}
    )
    assert result.valid is False
    assert "UNRECOGNIZED_SPINE_SCHEMA_ID" in result.blocking_codes


def test_vendor_digests_are_intact() -> None:
    """The vendored engine is byte-authentic at the pinned digest."""
    assert bridge.verify_vendor_digests() is None


# --------------------------------------------------------------------------- #
# 7. DETERMINISM
# --------------------------------------------------------------------------- #


def test_projection_is_deterministic(pristine: dict) -> None:
    first = projector.project_packet(copy.deepcopy(pristine))
    second = projector.project_packet(copy.deepcopy(pristine))
    assert json.dumps(first, sort_keys=True) == json.dumps(second, sort_keys=True)


def test_golden_projection_fixture_is_byte_stable(pristine: dict) -> None:
    golden_dir = REPO_ROOT / "tests" / "fixtures" / "governance" / "spine_projection"
    projected = projector.project_packet(pristine)
    assert len(projected) == 1
    obj = projected[0]
    ref = obj["bioactivityExposureRatioRecordId"].replace(":", "_")
    golden = (
        golden_dir
        / f"pristine_prioritize_risk_signals__BioactivityExposureRatioRecord__{ref}.json"
    )
    assert golden.exists()
    assert json.loads(golden.read_text(encoding="utf-8")) == obj
