name: Docs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.11"

      - name: Install project (editable)
        run: pip install -e .

      - name: Build and validate docs
        run: bash scripts/build_docs.sh
